#!/bin/sh
set -e

# Post-installation script for badgerdrop

        # Set badgerdrop as default handler for AppImage files
            xdg-mime default badgerdrop.desktop application/x-appimage
        fi
        ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
