#!/bin/sh
set -e

# Pre-removal script for appimg

case "$1" in
    remove|upgrade|deconfigure)
        # Remove appimg as default handler (restore to nothing)
        if [ -x /usr/bin/xdg-mime ]; then
            # We don't set a new default, user can choose another
            :
        fi
        ;;
    
    failed-upgrade)
        ;;
    
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
